### PR TITLE
Make 'save_path' compatible for UNIX-like systems

### PR DESCRIPTION
**Pull request by form-follows-function**
Also adds an UX-friendly behaviour for saved or unsaved files

### CODE REVIEW

**Comment by form-follows-function** [comment]
@Shahzod114 Somehow Github saw this as two seperated commits, but it's just one.

Would be glad if you could test this on a Windows Environment.

**Comment by form-follows-function** [comment]
> Also adds an UX-friendly behaviour for saved or unsaved files

Which means it fallbacks to the user's home directory if the file wasn't saved yet.

**Comment by Shahzod114** [comment]
Thanks, tested on windows and works fine. But, it doesn't let me select path if blend file is not saved. I think line 65 should be:
`if bpy.data.is_saved:`

**Comment by form-follows-function** [comment]
> Thanks, tested on windows and works fine. But, it doesn't let me select a path if blend file is not saved. I think line 65 should be:
> `if bpy.data.is_saved:`

You are right.
I've fixed the commit

**Review by Shahzod114 — APPROVED** [review]

**Review by Shahzod114 — APPROVED** [review]

**Pull request merged**
